spring:
  application:
    name: products
  profiles: dev
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/projectdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
